apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: predict-deployment
  labels:
      deployment: predict
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25% # default
      maxUnavailable: 25% # default
  template:
    metadata:
      labels:
        app: predict
        version: 1.0.1
    spec:
      containers:
        - name: predict
          image: gcr.io/nmiu-play/predict:1.0.1
          resources:
            requests:
              memory: 1024M
              cpu: 500m # == 0.5
            limits:
              memory: 1536M
              cpu: 1
          ports:
            - containerPort: 8080
              name: predict-local
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_ah/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /_ah/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            timeoutSeconds: 5
