apiVersion: v1
kind: Service
metadata:
  name: predict-deployment
  labels:
    app: predict
    version: 1.0.1
spec:
  selector:
    app: predict
    version: 1.0.1
  ports:
    - name: http
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
